import { StyleSheet, Dimensions } from "react-native";
import { THEME } from "../constants/theme";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: THEME.background },
  scrollContent: { padding: 16, paddingBottom: 100 },
  mainHeader: { backgroundColor: THEME.primary, paddingBottom: 10 },
  logoRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', height: 60, position: 'relative' },
  headerLogoContainer: { alignItems: 'center', justifyContent: 'center', flex: 1 },
  headerLogo: { width: 220, height: 60 }, 
  accountRow: { flexDirection: "row", justifyContent: "flex-end", paddingHorizontal: 16, gap: 10, marginBottom: 6 },
  accountButton: { backgroundColor: "rgba(255,255,255,0.2)", paddingHorizontal: 12, paddingVertical: 6, borderRadius: 16 },
  accountButtonText: { color: THEME.white, fontWeight: "600", fontSize: 12 },
  headerBar: { height: 60, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, backgroundColor: THEME.white, borderBottomWidth: 1, borderColor: THEME.borderColor },
  headerTitle: { fontSize: 18, fontWeight: 'bold', color: THEME.textDark },
  headerCenterAbsolute: { position: 'absolute', left: 0, right: 0, alignItems: 'center', zIndex: -1 },
  headerBackButton: { padding: 10 },
  headerBackText: { fontSize: 24, color: THEME.primary },
  contentArea: { flex: 1, backgroundColor: THEME.background, borderTopLeftRadius: 20, borderTopRightRadius: 20, marginTop: -15, overflow: 'hidden' },
  categoryContainer: { marginTop: 5 },
  categoryPill: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 20, backgroundColor: 'rgba(255,255,255,0.2)', marginRight: 8, borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)' },
  categoryPillActive: { backgroundColor: THEME.secondary, borderColor: THEME.secondaryDark },
  categoryPillText: { color: THEME.white, fontWeight: '600' },
  categoryPillTextActive: { color: THEME.textDark, fontWeight: 'bold' },
  sliderSection: { paddingTop: 20 },
  sliderContainer: { height: 180, marginHorizontal: 16, borderRadius: 16, overflow: 'hidden', elevation: 5, shadowColor: "#000", shadowOffset: {width:0, height:2}, shadowOpacity: 0.2, shadowRadius: 4, backgroundColor: THEME.white },
  slideItem: { height: 180 },
  slideImage: { width: '100%', height: '100%' },
  dotsContainer: { position: 'absolute', bottom: 10, left: 0, right: 0, flexDirection: 'row', justifyContent: 'center' },
  dot: { width: 8, height: 8, borderRadius: 4, backgroundColor: 'rgba(255,255,255,0.5)', marginHorizontal: 4 },
  dotActive: { backgroundColor: THEME.secondary, width: 20 },
  brandScroll: { marginTop: 20, height: 80 },
  brandCircle: { width: 64, height: 64, borderRadius: 32, backgroundColor: THEME.white, marginRight: 12, justifyContent: 'center', alignItems: 'center', elevation: 2, shadowColor: "#000", shadowOpacity: 0.1, shadowRadius: 2 },
  brandImg: { width: 40, height: 40 },
  productsSection: { padding: 16 },
  sectionTitle: { fontSize: 20, fontWeight: 'bold', color: THEME.textDark, marginBottom: 16 },
  sectionHeader: { fontSize: 18, fontWeight: 'bold', color: THEME.textDark, marginBottom: 12 },
  gridContainer: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
  noProductText: { textAlign: 'center', color: THEME.textGray, marginTop: 20 },
  emptyText: { textAlign: 'center', color: THEME.textGray, marginBottom: 12 },
  productCard: { width: (Dimensions.get("window").width - 48) / 2, backgroundColor: THEME.white, borderRadius: 12, marginBottom: 16, elevation: 3, shadowColor: "#000", shadowOpacity: 0.1, shadowOffset: { width: 0, height: 2 }, shadowRadius: 4, overflow: 'hidden' },
  productImageContainer: { height: 140, justifyContent: 'center', alignItems: 'center', backgroundColor: '#fff', padding: 10 },
  productImage: { width: '80%', height: '80%', resizeMode: 'contain' },
  productInfoContainer: { padding: 10, backgroundColor: '#FAFAFA' },
  productName: { fontSize: 14, color: THEME.textDark, height: 40, fontWeight: '500' },
  productBrand: { fontSize: 12, color: THEME.textGray, marginTop: 4 },
  productDescriptionPreview: { fontSize: 12, color: THEME.textGray, marginTop: 4 },
  outOfStockBadge: { marginTop: 8, alignSelf: 'flex-start', backgroundColor: THEME.danger, color: THEME.white, paddingHorizontal: 8, paddingVertical: 2, borderRadius: 6, fontSize: 11, fontWeight: '700', overflow: 'hidden' },
  productBottomRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 8 },
  productPrice: { fontSize: 16, fontWeight: 'bold', color: THEME.primary },
  addButton: { backgroundColor: THEME.secondary, paddingHorizontal: 12, paddingVertical: 6, borderRadius: 6 },
  addButtonText: { fontSize: 12, fontWeight: 'bold', color: THEME.textDark },
  addButtonDisabled: { backgroundColor: THEME.borderColor },
  addButtonTextDisabled: { color: THEME.textGray },
  counterContainer: { flexDirection: 'row', alignItems: 'center', backgroundColor: THEME.white, borderRadius: 6, borderWidth: 1, borderColor: THEME.borderColor },
  counterBtn: { paddingHorizontal: 8, paddingVertical: 2 },
  counterBtnText: { fontSize: 16, fontWeight: 'bold', color: THEME.primary },
  counterBtnDisabled: { backgroundColor: THEME.borderColor },
  counterBtnTextDisabled: { color: THEME.textGray },
  counterValue: { paddingHorizontal: 4, fontWeight: '600', fontSize: 14 },
  productCardDisabled: { opacity: 0.5 },
  emptyStateContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', marginTop: 100 },
  emptyStateIcon: { fontSize: 60, marginBottom: 20 },
  emptyStateTitle: { fontSize: 20, fontWeight: 'bold', color: THEME.textDark },
  emptyStateText: { textAlign: 'center', color: THEME.textGray, marginHorizontal: 40, marginTop: 10, marginBottom: 30 },
  cartListContainer: { padding: 16 },
  cartItemCard: { flexDirection: 'row', backgroundColor: THEME.white, borderRadius: 12, padding: 12, marginBottom: 12, elevation: 2 },
  cartItemImage: { width: 60, height: 60, resizeMode: 'contain', marginRight: 12 },
  cartItemInfo: { flex: 1, justifyContent: 'center' },
  cartItemName: { fontSize: 14, fontWeight: '600', color: THEME.textDark },
  cartItemSinglePrice: { fontSize: 12, color: THEME.textGray, marginTop: 4 },
  cartItemActions: { alignItems: 'flex-end', justifyContent: 'space-between' },
  cartItemTotalPrice: { fontSize: 16, fontWeight: 'bold', color: THEME.primary, marginTop: 4 },
  quantityControlSmall: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#F3F4F6', borderRadius: 8 },
  qtyBtnSmall: { padding: 6, width: 30, alignItems: 'center' },
  qtyBtnTextSmall: { fontSize: 16, fontWeight: 'bold', color: THEME.textDark },
  qtyBtnSmallDisabled: { opacity: 0.5 },
  qtyBtnTextSmallDisabled: { color: THEME.textGray },
  qtyTextSmall: { fontSize: 14, fontWeight: 'bold', width: 20, textAlign: 'center' },
  footerContainer: { position: 'absolute', bottom: 0, left: 0, right: 0, backgroundColor: THEME.white, padding: 20, borderTopLeftRadius: 24, borderTopRightRadius: 24, elevation: 20, shadowColor: "#000", shadowOpacity: 0.1 },
  footerRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 },
  footerLabel: { color: THEME.textGray, fontSize: 14 },
  footerValue: { color: THEME.textDark, fontSize: 14, fontWeight: '600' },
  divider: { height: 1, backgroundColor: THEME.borderColor, marginVertical: 12 },
  footerTotalRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 16 },
  footerTotalLabel: { fontSize: 18, fontWeight: 'bold', color: THEME.textDark },
  footerTotalValue: { fontSize: 18, fontWeight: 'bold', color: THEME.primary },
  summaryTotalRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 16 },
  primaryButton: { backgroundColor: THEME.secondary, paddingVertical: 16, borderRadius: 12, alignItems: 'center' },
  primaryButtonText: { color: THEME.textDark, fontSize: 16, fontWeight: 'bold' },
  secondaryButton: { backgroundColor: THEME.primary, paddingVertical: 12, paddingHorizontal: 24, borderRadius: 12 },
  secondaryButtonText: { color: THEME.white, fontWeight: 'bold' },
  disabledButton: { backgroundColor: THEME.borderColor },
  dashedButton: { borderWidth: 1, borderColor: THEME.primary, borderStyle: 'dashed', borderRadius: 12, padding: 16, alignItems: 'center', marginTop: 12, backgroundColor: THEME.primaryLight },
  dashedButtonText: { color: THEME.primary, fontWeight: 'bold' },
  footerSimple: { padding: 16, backgroundColor: THEME.white, borderTopWidth: 1, borderColor: THEME.borderColor },
  input: { backgroundColor: THEME.white, borderWidth: 1, borderColor: THEME.borderColor, borderRadius: 8, padding: 12, fontSize: 16, marginBottom: 12, color: THEME.textDark },
  inputLabel: { fontSize: 14, fontWeight: '600', color: THEME.textDark, marginBottom: 6 },
  selectionCard: { backgroundColor: THEME.white, padding: 16, borderRadius: 12, marginBottom: 12, borderWidth: 1, borderColor: THEME.borderColor },
  selectionCardActive: { borderColor: THEME.secondary, backgroundColor: '#FFFDF5', borderWidth: 2 },
  selectionHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 },
  defaultBadge: { marginLeft: 8, color: THEME.success, fontWeight: "700", fontSize: 12 },
  linkText: { color: THEME.primary, fontWeight: "600" },
  radioIcon: { fontSize: 18, color: THEME.secondary, marginRight: 8 },
  selectionTitle: { fontWeight: 'bold', color: THEME.textDark },
  selectionDetail: { color: THEME.textGray, fontSize: 13, marginLeft: 24 },
  deleteText: { color: THEME.danger, fontSize: 12 },
  summaryCard: { backgroundColor: THEME.white, padding: 16, borderRadius: 12, marginBottom: 16 },
  summarySectionTitle: { fontSize: 16, fontWeight: 'bold', color: THEME.primary, marginBottom: 8 },
  summaryTextBold: { fontWeight: '600', color: THEME.textDark },
  summaryText: { color: THEME.textGray, fontSize: 14 },
  summaryItemRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 6 },
  summaryItemName: { fontSize: 14, color: THEME.textDark, flex: 1 },
  summaryItemPrice: { fontWeight: '600', color: THEME.textDark },
  legalContainer: { marginTop: 20, alignItems: 'center' },
  legalLink: { color: THEME.textLight, fontSize: 12, textDecorationLine: 'underline', marginBottom: 6 },
  legalLogosRow: { flexDirection: 'row', marginTop: 12, justifyContent: 'center' },
  paymentLogo: { width: 50, height: 30, marginHorizontal: 6 },
  successContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 32, backgroundColor: THEME.white },
  successCircle: { width: 100, height: 100, borderRadius: 50, backgroundColor: '#D1FAE5', justifyContent: 'center', alignItems: 'center', marginBottom: 24 },
  successTitle: { fontSize: 24, fontWeight: 'bold', color: THEME.textDark, marginBottom: 12 },
  successText: { fontSize: 16, textAlign: 'center', color: THEME.textGray, marginBottom: 24 },
  successSubText: { fontSize: 14, textAlign: 'center', color: THEME.textLight, marginBottom: 40 },
  floatingCart: { position: 'absolute', right: 0, left: 0 },
  floatingBtnInner: { flexDirection: 'row', backgroundColor: THEME.secondary, marginHorizontal: 16, borderRadius: 16, padding: 12, alignItems: 'center', justifyContent: 'space-between', elevation: 10, shadowColor: THEME.secondary, shadowOffset: {width:0, height:4}, shadowOpacity: 0.5 },
  cartIconWrapper: { flexDirection: 'row', alignItems: 'center' },
  badge: { backgroundColor: THEME.white, borderRadius: 10, paddingHorizontal: 6, paddingVertical: 2, marginLeft: 8 },
  badgeText: { color: THEME.primary, fontWeight: 'bold', fontSize: 12 },
  floatingTotal: { backgroundColor: 'rgba(0,0,0,0.1)', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8 },
  floatingTotalText: { color: THEME.textDark, fontWeight: 'bold', fontSize: 16 },
});
